### ISSUE TITLE
YAML parser panic

### ISSUE THREAD

**Issue by slrtbtfs** [slrtbtfs/promql-lsp#67]
In some cases the YAML parser used by the language server panics.

To prevent this from crashing the whole language server, these panics should be recovered.

Ideally all of these crashes should also be reported and fixed upstream.

**Comment by slrtbtfs** [comment]
Here's a stacktrace:

```
panic: internal error: attempted to parse unknown event (please report): none [recovered]
	panic: internal error: attempted to parse unknown event (please report): none

goroutine 44 [running]:
gopkg.in/yaml%2ev3.handleErr(0xc0008ffe20)
	/home/slrtbtfs/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20191107175235-0b070bb63a18/yaml.go:276 +0x9a
panic(0x8e18e0, 0xc00090c9c0)
	/usr/lib/golang/src/runtime/panic.go:679 +0x1b2
gopkg.in/yaml%2ev3.(*parser).parse(0xc000186c00, 0x992ea0)
	/home/slrtbtfs/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20191107175235-0b070bb63a18/decode.go:158 +0x28c
gopkg.in/yaml%2ev3.(*parser).parseChild(0xc000186c00, 0xc00094ac80, 0xc00094b180)
	/home/slrtbtfs/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20191107175235-0b070bb63a18/decode.go:186 +0x2f
gopkg.in/yaml%2ev3.(*parser).mapping(0xc000186c00, 0xc00094a609)
	/home/slrtbtfs/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20191107175235-0b070bb63a18/decode.go:269 +0x10a
gopkg.in/yaml%2ev3.(*parser).parse(0xc000186c00, 0xc000186c00)
	/home/slrtbtfs/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20191107175235-0b070bb63a18/decode.go:147 +0x1b8
gopkg.in/yaml%2ev3.(*parser).parseChild(0xc000186c00, 0xc0008dd180, 0xc00094a6e0)
	/home/slrtbtfs/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20191107175235-0b070bb63a18/decode.go:186 +0x2f
gopkg.in/yaml%2ev3.(*parser).sequence(0xc000186c00, 0xc0001e5807)
	/home/slrtbtfs/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20191107175235-0b070bb63a18/decode.go:251 +0xef
gopkg.in/yaml%2ev3.(*parser).parse(0xc000186c00, 0xc0008da1d0)
	/home/slrtbtfs/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20191107175235-0b070bb63a18/decode.go:149 +0x192
gopkg.in/yaml%2ev3.(*parser).parseChild(0xc000186c00, 0xc0008dc140, 0xc0008dd0e0)
	/home/slrtbtfs/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20191107175235-0b070bb63a18/decode.go:186 +0x2f
gopkg.in/yaml%2ev3.(*parser).mapping(0xc000186c00, 0xc0001cbc09)
	/home/slrtbtfs/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20191107175235-0b070bb63a18/decode.go:277 +0x1a6
gopkg.in/yaml%2ev3.(*parser).parse(0xc000186c00, 0x0)
	/home/slrtbtfs/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20191107175235-0b070bb63a18/decode.go:147 +0x1b8
gopkg.in/yaml%2ev3.(*parser).parseChild(0xc000186c00, 0xc0008dc0a0, 0x0)
	/home/slrtbtfs/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20191107175235-0b070bb63a18/decode.go:186 +0x2f
gopkg.in/yaml%2ev3.(*parser).document(0xc000186c00, 0x3)
	/home/slrtbtfs/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20191107175235-0b070bb63a18/decode.go:195 +0x94
gopkg.in/yaml%2ev3.(*parser).parse(0xc000186c00, 0xc0000f0070)
	/home/slrtbtfs/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20191107175235-0b070bb63a18/decode.go:151 +0x133
gopkg.in/yaml%2ev3.(*Decoder).Decode(0xc0001cbe98, 0x93fc40, 0xc0008f8000, 0x0, 0x0)
	/home/slrtbtfs/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20191107175235-0b070bb63a18/yaml.go:123 +0x118
github.com/slrtbtfs/promql-lsp/langserver/cache.(*Document).parseYamls(0xc0000b4340, 0xa65000, 0xc000206480, 0x38, 0xc00013b6d0)
	/home/slrtbtfs/git/github.com/slrtbtfs/promql-lsp/langserver/cache/yaml.go:51 +0x298
github.com/slrtbtfs/promql-lsp/langserver/cache.(*Document).compile(0xc0000b4340, 0xa65000, 0xc000206480, 0x0, 0x0)
	/home/slrtbtfs/git/github.com/slrtbtfs/promql-lsp/langserver/cache/compile.go:39 +0x20c
created by github.com/slrtbtfs/promql-lsp/langserver/cache.(*Document).SetContent
	/home/slrtbtfs/git/github.com/slrtbtfs/promql-lsp/langserver/cache/document.go:132 +0x255
[Info  - 12:22:01 PM] Connection to server got closed. Server will restart.
[Error - 12:22:01 PM] Request textDocument/completion failed.
```

**Comment by slrtbtfs** [comment]
And a minimal example that triggers a chrash:

```
a:
.
-
```

**Comment by slrtbtfs** [comment]
And a upstream bug report:

https://github.com/go-yaml/yaml/issues/560
